#! /bin/bash
set -Eeu -o pipefail

if [ "$#" -lt 2 ]; then
  echo "Usage: jmx_exporter PORT CONFIG" >&2
  exit 1
fi

readonly JMX_EXPORTER_JAR="/usr/share/jmx_exporter/jmx_prometheus_httpserver.jar"
readonly JMX_EXPORTER_LISTEN="${@:$#-1:1}"
readonly JMX_EXPORTER_CONFIG_FILE="${@:$#:1}"
readonly JMX_EXPORTER_HOSTPORT=$(sed -ne 's/^hostPort: \(.*\)$/\1/p' "${JMX_EXPORTER_CONFIG_FILE}" | tr -d '\n')

# test readyness
java -cp "${JMX_EXPORTER_JAR}" "${@:1:$#-2}" io.prometheus.jmx.JmxScraper "service:jmx:rmi:///jndi/rmi://${JMX_EXPORTER_HOSTPORT}/jmxrmi" > /dev/null

exec java -jar "${JMX_EXPORTER_JAR}" "${@}"
