name: CI to Docker Hub 

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
   branches:
     - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [8, 11]
    steps:
      -
        name: Checkout
        id: checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build prometheus jmx exporter images
        id: build_images
        run: make all java_version=${{ matrix.java_version }} docker_org=${{ secrets.DOCKERHUB_USERNAME }} cache=/tmp/.buildx-cache
      -
        name: Login to DockerHub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push images
        id: push_images
        run: make push java_version=${{ matrix.java_version }} docker_org=${{ secrets.DOCKERHUB_USERNAME }} cache=/tmp/.buildx-cache
